# Generated by Django 5.1.6 on 2025-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Зображення')),
                ('button_text', models.CharField(default='Обрати', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.URLField(blank=True, verbose_name='Посилання кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Слайд каруселі',
                'verbose_name_plural': 'Слайди каруселі',
                'ordering': ['order'],
            },
        ),
    ]
