# Generated by Django 5.1.6 on 2025-05-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextCarouselMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст повідомлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Текстове повідомлення',
                'verbose_name_plural': 'Текстові повідомлення',
                'ordering': ['order'],
            },
        ),
    ]
