# Generated by Django 5.1.6 on 2025-05-04 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_textcarouselmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.AlterModelOptions(
            name='carouselslide',
            options={'ordering': ['order'], 'verbose_name': 'Карусель фото', 'verbose_name_plural': 'Карусель фото'},
        ),
        migrations.AlterModelOptions(
            name='textcarouselmessage',
            options={'ordering': ['order'], 'verbose_name': 'Елемент текстової каруселі', 'verbose_name_plural': 'Карусель текст'},
        ),
        migrations.AlterField(
            model_name='textcarouselmessage',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Елемент текстової каруселі'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.product')),
            ],
        ),
    ]
