# Generated by Django 5.1.6 on 2025-05-11 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartitem_product_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наявності'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Базові ноти'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Створено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловічий'), ('female', 'Жіночий'), ('unisex', 'Унісекс')], max_length=10, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Бестселер'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендований товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='middle_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Середні ноти'),
        ),
        migrations.AddField(
            model_name='product',
            name='scent_group',
            field=models.CharField(blank=True, choices=[('woody', 'Деревинні'), ('floral', 'Квіткові'), ('fresh and citrus', 'Свіжі та Цитрусові'), ('sweet and fruity', 'Солодкі та Фруктові'), ('oriental and spicy', 'Східні та Пряні'), ('leather', 'Шкіряні')], max_length=20, verbose_name='Група ароматів'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('3', '3 мл'), ('16', '16 мл'), ('100', '100 мл')], max_length=10, verbose_name='Обʼєм'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Верхні ноти'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='products', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
    ]
