# Generated by Django 5.1.6 on 2025-05-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_options_product_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='middle_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ноти серця'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('3', '3мл'), ('16', '16мл'), ('100', '100мл')], max_length=10, verbose_name='Обʼєм'),
        ),
    ]
