# Generated by Django 5.1.6 on 2025-05-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_options_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssortmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='slides/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
