# Generated by Django 5.1.6 on 2025-05-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_assortmentphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssortmentPhoto',
            new_name='ProductListPhoto',
        ),
    ]
