# Generated by Django 5.1.6 on 2025-05-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_assortmentphoto_productlistphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='scent_group',
            field=models.CharField(blank=True, choices=[('floral', 'Квіткові'), ('fresh and citrus', 'Свіжі та Цитрусові'), ('sweet and fruity', 'Солодкі та Фруктові'), ('oriental and spicy', 'Східні та Пряні')], max_length=20, verbose_name='Група ароматів'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('16', '16мл'), ('100', '100мл')], max_length=10, verbose_name='Обʼєм'),
        ),
    ]
