# Generated by Django 5.1.6 on 2025-05-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductPerfume',
        ),
    ]
