# Generated by Django 5.1.6 on 2025-05-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_product_productperfume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('picture', models.ImageField(blank=True, default='', upload_to='products', verbose_name='Зображення')),
                ('available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('scent_group', models.CharField(blank=True, choices=[('woody', 'Деревинні'), ('floral', 'Квіткові'), ('sweet and fruity', 'Солодкі та Фруктові')], max_length=20, verbose_name='Група ароматів')),
                ('top_notes', models.CharField(blank=True, max_length=255, verbose_name='Верхні ноти')),
                ('middle_notes', models.CharField(blank=True, max_length=255, verbose_name='Ноти серця')),
                ('base_notes', models.CharField(blank=True, max_length=255, verbose_name='Базові ноти')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований товар')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Бестселер')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
