# Generated by Django 5.1.6 on 2025-05-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productperfume_is_scent_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='productperfume',
            name='is_darkfem_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productperfume',
            name='is_loveme_collection',
            field=models.BooleanField(default=False),
        ),
    ]
