# Generated by Django 5.1.6 on 2025-05-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productperfume',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловічий'), ('female', 'Жіночий'), ('unisex', 'Унісекс')], max_length=10, null=True, verbose_name='Стать'),
        ),
    ]
